name: "GFS forecast"
description: >-
  This addon grabs GFS information from the NOAA NOMADS server
url: https://github.com/MarcoGos/ha-addons
version: "0.0.6"
slug: gfsforecast
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
apparmor: true
stdin: true
options:
  log_level: info
  max_offset: 168
  unit_system: Metric
schema:
  log_level: list(debug|info|warning|error|fatal|critical)?
  max_offset: int(1,384)
  unit_system: "list(Imperial|Metric)"
  detailed: bool?
init: false
image: "marcogos/{arch}-addon-gfsforecast"