name: "GFS Weather Forecast"
description: >-
  This addon grabs the GFS weather forecast modal data from the NWS NCEP nomads server. The addon works in conjunction with the GFS Weather Forecast integration
url: https://github.com/MarcoGos/ha-addons
version: "2.0.11"
slug: gfsweatherforecast
arch:
  - aarch64
  - amd64
homeassistant_api: true
apparmor: true
map:
  - type: addon_config
    read_only: false
    path: /addon_config
options:
  log_level: info
  max_offset: 225
  language: en
schema:
  log_level: list(debug|info|warning|error|fatal|critical)?
  max_offset: int(1,384)
  language: list(en|nl)
init: false
ports:
  8000/tcp: 8000
  8001/tcp: 8001
ports_description:
  8000/tcp: Port for API calls, used by the GFS weather forecast integration
  8001/tcp: Port for the web interface, used by the GFS weather forecast integration
image: "marcogos/{arch}-addon-gfs_weather_forecast"
