name: Vantage Pro to MQTT
description: >-
  Vantage Pro Weather to MQTT gateway. Using the pyvantagepro library
url: https://github.com/MarcoGos/homeassistant_vantagepro2mqtt/
version: "0.0.1"
slug: "vantagepro2mqtt"
arch:
  - aarch64
  - amd64
  - armhf
apparmor: true
options:
  device: null
  interval: 30
  unit_system: Metric
  new_sensor_used: false
  log_level: notice
schema:
  device: device(subsystem=tty)
  interval: "int"
  unit_system: "list(Imperial|Metric)"
  new_sensor_used: "bool"
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  mqtt_host: "str?"
  mqtt_port: "port?"
  mqtt_user: "str?"
  mqtt_pass: "str?"
  discovery_prefix: "str?"
init: false
uart: true
services:
  - mqtt:need
stage: "experimental"