name: Vantage Pro Weather to MQTT
description: >-
  Vantage Pro Weather to MQTT gateway. Based on vproweather
url: https://github.com/MarcoGos/homeassistant_vproweather/
version: "1.0.3"
slug: "vproweather2mqtt"
arch:
  - aarch64
  - amd64
  - armhf
apparmor: true
options:
  device: null
  interval: 50
  use_metric: true
schema:
  device: device(subsystem=tty)
  interval: "int"
  use_metric: "bool"
  new_sensor_used: "bool?"
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_user: "str?"
  mqtt_pass: "str?"
init: false
uart: true
services:
  - mqtt:need
stage: "experimental"